# Generated by Django 3.2.4 on 2021-06-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0003_auto_20210621_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategorie', 'verbose_name_plural': 'kategorie'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'donacje', 'verbose_name_plural': 'donacje'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'instytucje', 'verbose_name_plural': 'instytucje'},
        ),
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
