# Generated by Django 3.2.4 on 2021-06-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0005_alter_donation_pick_up_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='closing_date',
            field=models.DateField(default=None),
        ),
    ]
