# Generated by Django 3.2.4 on 2021-07-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0009_alter_donation_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
